version: '3.8'


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  create_tables:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: python /app/create_tables.py

  insert_data:
    build: .
    depends_on:
      - create_tables
      - postgres
    volumes:
      - .:/app
    command: python /app/main.py


volumes:
  postgres_data:
