version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python_processor_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_processor_1
    volumes:
      - ./processor_code:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/postgres
    command: python /app/processor_1.py

  python_processor_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_processor_2
    volumes:
      - ./processor_code:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/postgres
    command: python /app/processor_2.py

  python_processor_3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_processor_3
    volumes:
      - ./processor_code:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/postgres
    command: python /app/processor_3.py

volumes:
  pgdata:
