services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  create_tables:
    image: create_tables:latest
    build: ./mock
    depends_on:
      - postgres
    volumes:
      - ./mock:/app
    command: python create_tables.py

  insert_data:
    image: insert_data:latest
    build: ./mock
    depends_on:
      - create_tables
      - postgres
    volumes:
      - ./mock:/app
    command: python main.py

  
  spark-historic-app:
    image: spark-historic-app:latest
    build: ./server
    depends_on:
      - create_tables
      - postgres
    environment:
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./mock/mock_files:/historic_spark/mock_files
      - ./tasks:/historic_spark/tasks
    command: python historic_data_processor.py


volumes:
  postgres_data:
