version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis_filler:
    build: ./redis_filler
    container_name: redis_filler
    depends_on:
      - redis

  flask_app:
    build: ./flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
