version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  streamlit:
    build:
      context: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  filler:
    build:
      context: ./redis_filler
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
