services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Default RabbitMQ user (change in production)
      RABBITMQ_DEFAULT_PASS: guest  # Default RabbitMQ password (change in production)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      retries: 10
      
  webhook:
    image: webhook:latest
    build: .
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: localhost
    network_mode: "host"
    restart: on-failure:always
    command: python webhook.py

  client:
    image: client:latest
    build: .
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: localhost
    network_mode: "host"
    restart: on-failure:always
    command: python example_client.py